dist: trusty
sudo: required
services:
- docker
language: node_js
node_js:
- 9.5.0
branches:
  except:
  - "/\\+travis\\.\\d+$/"
  - "/^\\d+\\.\\d+\\.\\d+-\\d+$/"
env:
  global:
  - ATOMIST_TEAM=T29E48P34
  - NPM_PUBLISH=true
  - NPM_REGISTRY=https://atomist.jfrog.io/atomist/api/npm/npm-dev-local
  - secure: bz3asJvKfwgpTEit35x81c8lNJI1KBw+FaJoWMkaWtdXabgiSdOM1bnZz9rvsu3d4Gg3gcn6BvLmHdDi2N1gjAR2RIIE6zUbafibwb/Chs77Bhb00l2fbaONU0/IzhC9NiUzuS0ZFaCloDDmw53SiDSIIfo1z+2VT+5TYZJ7TIpRZQi+AtT3GYweViwa2ae9JcH/FYnpLAaV+Rzh6Sm6kE+l2GAFnxRok8oPA/r7ZQj01QVWidDPGPWkihb93C81ceIYyhyAFmjiN+NNevuRFgvsuISMjsUHNHfDuZKe/QqRCYT0TrqROdjhHeoANwussk045QQeHoS23f7rjB2F/KRDJR8PQ+MQE70ZVRf+AE3bogg4ek3gLGPNGyj4r7gEG9rd66jmSymsdLZc8V7kk5wNLU2lmRcJqaMIka0tTxBEjoNmmgYj0vPnwkytLBc8nBFciXoRKhwPolvHmSTlTmHPlb+QH5o1ufCZWK5+JrwvsWDysLdXBwXxRTVFM3DS+wrTk4M+ZxElrfECA9Ucq5KJd4ZWixarW90OxRJJafHlRtU25R09enU2KXZBoya3yqXnFaUI4jyOQ7NYMsP3CqPvrtgFmXn9kHNhIbuejLvgq3NLtLaOuijxy7FlMgWeduPrPdHDUd9q6Nrx+ip+8/gm9padq6FZ/H3ivRUmc8E=
  - DOCKER_REGISTRY=atomist
  - DOCKER_USER=atomist
  - secure: FUbpx9efJGkZzR5BQFeMHAi9cEz7T6aoYn17tERu0/0dJ8KoSERJ/3bYVV+/wnT+s0/yo86XWEd0AI4985BpjRFtgGVQEFbtU1IdmjgfCgsGsoNTS/V5PscpTLf8eIa6iXjybdlvaRi5fH4xPkJsEdIj1NOIVxn3DXA03dcy8ZFC2Oeq2WFU3MUOLsd+PQOHOqNMbPlxrIKwCciljnbNCbZMP7RT9Nf3Z0dBP0b6F9QhxM03y6vmPTMVrWXMlgw/Ed1zGVjINa8jirxQBi3syXCY6cAipK+Y2fLBRsuDRywA1B3+2kNOEAymuYoPSyaxnxWzH24M8C63LVSPlIGT4MlkLLdIHdQ+kvI2QHHgN9131+xmnXQWgRr+bmGKsC+dOW4nlWtpFO+JrVxdRlR8OfdkOjlNRcwSU3+/rd9fD/D8Eh4N/gp5OZ3/+J6JunKXKoOJKJ3GSczJbodEpazu8Dz0Sx0XCfM4ToCysGGH3uRY0jF9+rXHIdiQnyYrESPj45bQ4CYJSh82pjgx3r063PmyBY7MV4m1nhcDfTc7N2x2uzCltbXtVrRAWua//7RUD87wmXZqak0vrZtZ3v2XqkrV2WSdh7csv7xxyqn+zHQPK+Mi0nnnK2HYS+eNXp7HKo0jiu5lbzUvxklep+KqGeGc6ARF7zL6uFgP4gnPLZM=
before_install:
- openssl aes-256-cbc -K $encrypted_f1d3e3be3628_key -iv $encrypted_f1d3e3be3628_iv
  -in .npmrc.enc -out .npmrc -d
script: bash scripts/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/atomist/travis/teams/T29E48P34
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
before_deploy:
- touch build/typedoc/.nojekyll
deploy:
- provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: build/typedoc
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+(-(m|rc)\\.[0-9]+)?$"
- provider: releases
  api_key: "$GITHUB_TOKEN"
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+(-(m|rc)\\.[0-9]+)?$"
