---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: node-automation
  labels:
    app: node-automation
    owner: atomist
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: node-automation
      owner: atomist
  template:
    metadata:
      labels:
        app: node-automation
        owner: atomist
        version: "0"
    spec:
      containers:
      - name: node-automation
        image: atomist/node-automation:0.2.0
        imagePullPolicy: IfNotPresent
        env:
        - name: ATOMIST_CONFIG
          valueFrom:
            secretKeyRef:
              name: automation
              key: config
        ports:
        - name: http
          containerPort: 2866
          protocol: TCP
        livenessProbe:
          httpGet:
            path: "/health"
            port: 2866
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 3
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: "/health"
            port: 2866
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 3
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: 500m
            memory: 384Mi
          requests:
            cpu: 100m
            memory: 256Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 180
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
